controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Plugin routes - SortX
plugin_sortx:
    resource:
        path: /plugins/sortx/backend/Controller/
        namespace: Plugin\SortX\Controller
    type: attribute

# Plugin routes - BroGent
plugin_brogent:
    resource:
        path: /plugins/brogent/backend/Controller/
        namespace: Plugin\Brogent\Controller
    type: attribute
